import type {
  AudioTalkRow,
  CommonSpaceRoomRow,
  InquiryCardRow,
  InquiryCategoryRow,
  LearnEpisodeRow,
  LearnSeriesRow,
  LibraryItemRow,
  PracticeSessionRow,
  QuoteRow,
  SilencePresetRow,
} from "./types";

// Mock content mirroring supabase/seed.sql, so apps can run without a
// Supabase project. Temporary mock content is allowed only here and in the
// seed file -- never hard-coded inside UI components.
//
// The one placeholder audio asset. Consumers map this id to something they
// can actually play (the mobile app bundles a synthesized sample tone).
// Swapping the mock adapter for Supabase means real storage URLs instead,
// with no change to anything that reads it.
export const MOCK_BELL_ASSET_ID = "media-sample-bell";

const now = "2026-01-01T00:00:00.000Z";

export const mockPracticeSessions: PracticeSessionRow[] = [
  {
    id: "practice-morning-stillness",
    title: "Morning Stillness",
    description: "A gentle start to the day, settling the body before the mind.",
    category: "breath",
    meaning: "A short settling practice that gives the day a steady starting point instead of an abrupt one.",
    motive: "Use this when the day feels like it is starting before you have actually arrived in it.",
    completion_suggestion: "Notice one thing you can carry from this stillness into the next hour.",
    audio_asset_id: MOCK_BELL_ASSET_ID,
    cover_asset_id: null,
    duration_seconds: 600,
    status: "published",
    visibility: "free",
    sort_order: 1,
    created_at: now,
    updated_at: now,
  },
  {
    id: "practice-breath-awareness",
    title: "Breath Awareness",
    description: "A simple return to the breath, again and again.",
    category: "breath",
    meaning: "The breath is always available as a place to return attention, no matter what else is happening.",
    motive: "Use this when your thoughts are moving faster than you can follow.",
    completion_suggestion: "Take one more breath, slower than the rest, before you move on.",
    audio_asset_id: MOCK_BELL_ASSET_ID,
    cover_asset_id: null,
    duration_seconds: 480,
    status: "published",
    visibility: "free",
    sort_order: 2,
    created_at: now,
    updated_at: now,
  },
  {
    id: "practice-body-scan-release",
    title: "Body Scan Release",
    description: "Moving attention through the body, releasing held tension.",
    category: "body",
    meaning: "Tension often goes unnoticed until attention is deliberately moved through the body.",
    motive: "Use this when you feel tense but cannot point to why.",
    completion_suggestion: "Check in with your shoulders and jaw once more before you stand up.",
    audio_asset_id: MOCK_BELL_ASSET_ID,
    cover_asset_id: null,
    duration_seconds: 900,
    status: "published",
    visibility: "free",
    sort_order: 3,
    created_at: now,
    updated_at: now,
  },
  {
    id: "practice-loving-kindness",
    title: "Loving Kindness",
    description: "Extending warmth, first to yourself, then outward.",
    category: "heart",
    meaning: "Warmth directed inward first is what makes it possible to extend outward honestly.",
    motive: "Use this when you have been harder on yourself or others than the moment called for.",
    completion_suggestion: "Bring one person to mind and silently wish them well.",
    audio_asset_id: MOCK_BELL_ASSET_ID,
    cover_asset_id: null,
    duration_seconds: 720,
    status: "published",
    visibility: "free",
    sort_order: 4,
    created_at: now,
    updated_at: now,
  },
  {
    id: "practice-evening-wind-down",
    title: "Evening Wind-Down",
    description: "Letting the day settle before rest.",
    category: "sleep",
    meaning: "The day does not need to be resolved before rest, only set down.",
    motive: "Use this when the day is over but your mind has not caught up to that yet.",
    completion_suggestion: "Name one thing from today that you are willing to leave as it is.",
    audio_asset_id: MOCK_BELL_ASSET_ID,
    cover_asset_id: null,
    duration_seconds: 600,
    status: "published",
    visibility: "free",
    sort_order: 5,
    created_at: now,
    updated_at: now,
  },
];

export const mockSilencePresets: SilencePresetRow[] = [
  {
    id: "silence-5",
    title: "Quiet Sit -- 5 Minutes",
    description: "A short, unguided sit.",
    duration_seconds: 300,
    ambient_audio_asset_id: null,
    bell_interval_seconds: null,
    status: "published",
    visibility: "free",
    sort_order: 1,
    created_at: now,
    updated_at: now,
  },
  {
    id: "silence-10",
    title: "Quiet Sit -- 10 Minutes",
    description: "A steady, unguided sit with a midpoint bell.",
    duration_seconds: 600,
    ambient_audio_asset_id: null,
    bell_interval_seconds: 300,
    status: "published",
    visibility: "free",
    sort_order: 2,
    created_at: now,
    updated_at: now,
  },
  {
    id: "silence-20",
    title: "Quiet Sit -- 20 Minutes",
    description: "A longer unguided sit for an established practice.",
    duration_seconds: 1200,
    ambient_audio_asset_id: null,
    bell_interval_seconds: 600,
    status: "published",
    visibility: "free",
    sort_order: 3,
    created_at: now,
    updated_at: now,
  },
];

export const mockInquiryCategories: InquiryCategoryRow[] = [
  { id: "inquiry-cat-who-am-i", title: "Who Am I", description: "Looking past the roles and labels.", status: "published", visibility: "free", sort_order: 1, created_at: now, updated_at: now },
  { id: "inquiry-cat-relationships", title: "Relationships", description: "Where you meet others, and where you meet yourself.", status: "published", visibility: "free", sort_order: 2, created_at: now, updated_at: now },
  { id: "inquiry-cat-fear", title: "Fear", description: "What fear protects, and what it costs.", status: "published", visibility: "free", sort_order: 3, created_at: now, updated_at: now },
  { id: "inquiry-cat-purpose", title: "Purpose", description: "What you are moving toward, and why.", status: "published", visibility: "free", sort_order: 4, created_at: now, updated_at: now },
  { id: "inquiry-cat-presence", title: "Presence", description: "What is actually here, right now.", status: "published", visibility: "free", sort_order: 5, created_at: now, updated_at: now },
];

export const mockInquiryCards: InquiryCardRow[] = [
  {
    id: "inquiry-card-job-title",
    category_id: "inquiry-cat-who-am-i",
    prompt: "Who would you be without your job title?",
    question: "Who would you be without your job title?",
    answer: "Whatever is left when the title is removed -- not nothing, just unnamed.",
    explanation: "Roles are useful descriptions, not the thing being described.",
    reflection_prompt: "Sit with the discomfort of not having an answer ready.",
    mood_relevance: ["disconnected", "uncertain"],
    status: "published",
    visibility: "free",
    sort_order: 1,
    created_at: now,
    updated_at: now,
  },
  {
    id: "inquiry-card-judge-voice",
    category_id: "inquiry-cat-who-am-i",
    prompt: "Whose voice do you hear when you judge yourself?",
    question: "Whose voice do you hear when you judge yourself?",
    answer: "Often it is borrowed -- a parent, a teacher, an old rival.",
    explanation: "Self-judgment is rarely original. Noticing whose voice it is can loosen its grip.",
    reflection_prompt: "Ask whether you would say it to someone else.",
    mood_relevance: ["anxious", "sad"],
    status: "published",
    visibility: "free",
    sort_order: 2,
    created_at: now,
    updated_at: now,
  },
  {
    id: "inquiry-card-withhold-safe",
    category_id: "inquiry-cat-relationships",
    prompt: "What do you withhold to feel safe?",
    question: "What do you withhold to feel safe?",
    answer: "Usually something true, in exchange for not being seen too clearly.",
    explanation: "Withholding can feel protective, but it also keeps connection at a distance.",
    reflection_prompt: "Notice what you would risk saying if safety were not the priority.",
    mood_relevance: ["anxious", "lonely"],
    status: "published",
    visibility: "free",
    sort_order: 1,
    created_at: now,
    updated_at: now,
  },
  {
    id: "inquiry-card-avoiding",
    category_id: "inquiry-cat-fear",
    prompt: "What are you avoiding right now?",
    question: "What are you avoiding right now?",
    answer: "Something specific, even if the avoidance itself feels vague.",
    explanation: "Naming the avoided thing precisely is often more useful than analyzing the avoidance.",
    reflection_prompt: "Name it in one sentence, without softening it.",
    mood_relevance: ["anxious", "overwhelmed"],
    status: "published",
    visibility: "free",
    sort_order: 1,
    created_at: now,
    updated_at: now,
  },
  {
    id: "inquiry-card-no-one-watching",
    category_id: "inquiry-cat-purpose",
    prompt: "What would you do if no one were watching?",
    question: "What would you do if no one were watching?",
    answer: "Possibly something quieter and less impressive than your public version.",
    explanation: "Audience changes behavior more than most people notice in the moment.",
    reflection_prompt: "Try doing that thing once, with no one to tell.",
    mood_relevance: ["disconnected", "restless"],
    status: "published",
    visibility: "free",
    sort_order: 1,
    created_at: now,
    updated_at: now,
  },
  {
    id: "inquiry-card-breath-naming",
    category_id: "inquiry-cat-presence",
    prompt: "What does this breath feel like, without naming it?",
    question: "What does this breath feel like, without naming it?",
    answer: "Likely more textured and less uniform than the word \"breath\" suggests.",
    explanation: "Naming an experience can substitute for actually feeling it.",
    reflection_prompt: "Describe the sensation, not the label.",
    mood_relevance: ["restless", "anxious"],
    status: "published",
    visibility: "free",
    sort_order: 1,
    created_at: now,
    updated_at: now,
  },
];

export const mockLibraryItems: LibraryItemRow[] = [
  {
    id: "library-stillness-struggle",
    title: null,
    body: "Stillness is not the absence of motion, but the absence of struggle with it.",
    author: null,
    meaning: "Stillness can exist within activity once the struggle against it stops.",
    deeper_explanation: "This reframes stillness as an internal posture rather than something that requires quiet surroundings.",
    related_inquiry_card_id: null,
    status: "published",
    visibility: "free",
    sort_order: 1,
    created_at: now,
    updated_at: now,
  },
  {
    id: "library-breath-permission",
    title: null,
    body: "The breath has never once asked permission to continue.",
    author: null,
    meaning: "Breathing continues on its own, making it a dependable place to return attention.",
    deeper_explanation: "Because it requires no maintenance, the breath is available as an anchor in almost any state.",
    related_inquiry_card_id: "inquiry-card-breath-naming",
    status: "published",
    visibility: "free",
    sort_order: 2,
    created_at: now,
    updated_at: now,
  },
  {
    id: "library-resist-attention",
    title: null,
    body: "What you resist organizes your attention more than what you accept.",
    author: null,
    meaning: "Resisting an experience can fix attention on it more firmly than accepting it would.",
    deeper_explanation: "This is a common observation in contemplative practice -- fighting a feeling often amplifies its presence.",
    related_inquiry_card_id: "inquiry-card-avoiding",
    status: "published",
    visibility: "free",
    sort_order: 3,
    created_at: now,
    updated_at: now,
  },
  {
    id: "library-rest-earned",
    title: null,
    body: "Rest is not earned. It is available now.",
    author: null,
    meaning: "Rest does not need to be justified by output.",
    deeper_explanation: "Treating rest as a reward delays it indefinitely; it is available regardless.",
    related_inquiry_card_id: null,
    status: "published",
    visibility: "free",
    sort_order: 4,
    created_at: now,
    updated_at: now,
  },
  {
    id: "library-curiosity-judgment",
    title: null,
    body: "Curiosity is gentler than judgment, and it sees more.",
    author: null,
    meaning: "Curiosity stays open to what is actually there; judgment narrows it in advance.",
    deeper_explanation: "A curious question usually reveals more than a judgmental conclusion.",
    related_inquiry_card_id: "inquiry-card-judge-voice",
    status: "published",
    visibility: "free",
    sort_order: 5,
    created_at: now,
    updated_at: now,
  },
];

export const mockQuotes: QuoteRow[] = [
  { id: "quote-begin-where", body: "Begin where you are, not where you meant to be.", author: null, display_date: null, status: "published", visibility: "free", created_at: now, updated_at: now },
  { id: "quote-honest-breath", body: "One honest breath is worth more than ten distracted hours.", author: null, display_date: null, status: "published", visibility: "free", created_at: now, updated_at: now },
  { id: "quote-day-ask-less", body: "The day will ask less of you than your thoughts about the day.", author: null, display_date: null, status: "published", visibility: "free", created_at: now, updated_at: now },
  { id: "quote-not-behind", body: "You are not behind. There is no schedule for stillness.", author: null, display_date: null, status: "published", visibility: "free", created_at: now, updated_at: now },
  { id: "quote-today-breath", body: "Today only asks for this breath.", author: null, display_date: null, status: "published", visibility: "free", created_at: now, updated_at: now },
];

export const mockCommonSpaceRooms: CommonSpaceRoomRow[] = [
  {
    id: "room-morning-sit",
    title: "Morning Sit",
    description: "A shared quiet space to start the day.",
    room_type: "silence",
    is_public: true,
    duration_seconds: 600,
    purpose: "daily anchor",
    practice_session_id: null,
    status: "published",
    visibility: "free",
    sort_order: 1,
    created_at: now,
    updated_at: now,
  },
  {
    id: "room-evening-reflection",
    title: "Evening Reflection",
    description: "Wind down together at the end of the day.",
    room_type: "guided_practice",
    is_public: true,
    duration_seconds: 600,
    purpose: "wind down",
    practice_session_id: "practice-evening-wind-down",
    status: "published",
    visibility: "free",
    sort_order: 2,
    created_at: now,
    updated_at: now,
  },
  {
    id: "room-new-members",
    title: "New Members",
    description: "Say hello and get oriented.",
    room_type: "guided_practice",
    is_public: true,
    duration_seconds: 480,
    purpose: "onboarding",
    practice_session_id: "practice-breath-awareness",
    status: "published",
    visibility: "free",
    sort_order: 3,
    created_at: now,
    updated_at: now,
  },
  {
    id: "room-open-silence",
    title: "Open Silence",
    description: "No theme, no agenda -- just shared stillness.",
    room_type: "silence",
    is_public: true,
    duration_seconds: 1200,
    purpose: "open-ended practice",
    practice_session_id: null,
    status: "published",
    visibility: "free",
    sort_order: 4,
    created_at: now,
    updated_at: now,
  },
];

export const mockLearnSeries: LearnSeriesRow[] = [
  { id: "learn-foundations", title: "Foundations of Stillness", description: "The basics of sitting, breathing, and returning attention.", cover_asset_id: null, status: "published", visibility: "free", sort_order: 1, created_at: now, updated_at: now },
  { id: "learn-difficult-emotions", title: "Working with Difficult Emotions", description: "Meeting fear, anger, and grief without being run by them.", cover_asset_id: null, status: "published", visibility: "free", sort_order: 2, created_at: now, updated_at: now },
  { id: "learn-inquiry", title: "The Practice of Inquiry", description: "Using direct questions to look past assumption.", cover_asset_id: null, status: "published", visibility: "free", sort_order: 3, created_at: now, updated_at: now },
];

export const mockLearnEpisodes: LearnEpisodeRow[] = [
  { id: "learn-foundations-1", series_id: "learn-foundations", title: "Taking Your Seat", audio_asset_id: MOCK_BELL_ASSET_ID, duration_seconds: 420, episode_number: 1, status: "published", visibility: "free", created_at: now, updated_at: now },
  { id: "learn-foundations-2", series_id: "learn-foundations", title: "Following the Breath", audio_asset_id: MOCK_BELL_ASSET_ID, duration_seconds: 480, episode_number: 2, status: "published", visibility: "free", created_at: now, updated_at: now },
  { id: "learn-foundations-3", series_id: "learn-foundations", title: "Beginning Again", audio_asset_id: MOCK_BELL_ASSET_ID, duration_seconds: 480, episode_number: 3, status: "published", visibility: "free", created_at: now, updated_at: now },
  { id: "learn-emotions-1", series_id: "learn-difficult-emotions", title: "Naming What Is Here", audio_asset_id: MOCK_BELL_ASSET_ID, duration_seconds: 540, episode_number: 1, status: "published", visibility: "free", created_at: now, updated_at: now },
  { id: "learn-emotions-2", series_id: "learn-difficult-emotions", title: "Making Room for Fear", audio_asset_id: MOCK_BELL_ASSET_ID, duration_seconds: 600, episode_number: 2, status: "published", visibility: "free", created_at: now, updated_at: now },
  { id: "learn-emotions-3", series_id: "learn-difficult-emotions", title: "Anger Without Armor", audio_asset_id: MOCK_BELL_ASSET_ID, duration_seconds: 540, episode_number: 3, status: "published", visibility: "free", created_at: now, updated_at: now },
  { id: "learn-inquiry-1", series_id: "learn-inquiry", title: "Asking Without Answering", audio_asset_id: MOCK_BELL_ASSET_ID, duration_seconds: 480, episode_number: 1, status: "published", visibility: "free", created_at: now, updated_at: now },
  { id: "learn-inquiry-2", series_id: "learn-inquiry", title: "Looking Past the Label", audio_asset_id: MOCK_BELL_ASSET_ID, duration_seconds: 540, episode_number: 2, status: "published", visibility: "free", created_at: now, updated_at: now },
  { id: "learn-inquiry-3", series_id: "learn-inquiry", title: "Living with a Question", audio_asset_id: MOCK_BELL_ASSET_ID, duration_seconds: 600, episode_number: 3, status: "published", visibility: "free", created_at: now, updated_at: now },
];

export const mockAudioTalks: AudioTalkRow[] = [
  { id: "talk-letting-go", title: "On Letting Go", description: "What it actually means to release something.", speaker: "Within Teachers", audio_asset_id: MOCK_BELL_ASSET_ID, duration_seconds: 1080, status: "published", visibility: "free", sort_order: 1, created_at: now, updated_at: now },
  { id: "talk-nature-of-awareness", title: "The Nature of Awareness", description: "Looking at the one who is looking.", speaker: "Within Teachers", audio_asset_id: MOCK_BELL_ASSET_ID, duration_seconds: 1320, status: "published", visibility: "free", sort_order: 2, created_at: now, updated_at: now },
  { id: "talk-discomfort", title: "Sitting with Discomfort", description: "Why avoidance costs more than the discomfort itself.", speaker: "Within Teachers", audio_asset_id: MOCK_BELL_ASSET_ID, duration_seconds: 960, status: "published", visibility: "free", sort_order: 3, created_at: now, updated_at: now },
  { id: "talk-returning-breath", title: "Returning to the Breath", description: "The simplest practice, and why it is enough.", speaker: "Within Teachers", audio_asset_id: MOCK_BELL_ASSET_ID, duration_seconds: 840, status: "published", visibility: "free", sort_order: 4, created_at: now, updated_at: now },
  { id: "talk-silence-teacher", title: "Silence as Teacher", description: "What silence reveals that conversation cannot.", speaker: "Within Teachers", audio_asset_id: MOCK_BELL_ASSET_ID, duration_seconds: 1200, status: "published", visibility: "free", sort_order: 5, created_at: now, updated_at: now },
];
