export interface Episode {
  id: string;
  title: string;
  subtitle?: string;
  completed: boolean;
}

export interface Series {
  id: string;
  title: string;
  description: string;
  depth: "Beginner" | "Intermediate" | "Deep";
  episodes: Episode[];
}

export const seriesData: Series[] = [
  {
    id: "architecture-of-desire",
    title: "The Architecture of Desire",
    description: "The science of intentionality and the blueprint of the soul",
    depth: "Beginner",
    episodes: [
      { id: "1", title: "The Deep Want", subtitle: "What do you really want?", completed: true },
      { id: "2", title: "Precision Engineering", subtitle: "The difference between a wish and an intention", completed: true },
      { id: "3", title: "Thinking About What You Want", completed: true },
      { id: "4", title: "The Practice of Gratitude", completed: false },
      { id: "5", title: "The Silent Chamber", completed: false },
      { id: "6", title: "Navigating the Fog", completed: false },
      { id: "7", title: "The Social Mirror", completed: false },
      { id: "8", title: "The Rhythm of Attention", completed: false },
      { id: "9", title: "The Anatomy of Progress", completed: false },
      { id: "10", title: "The Wisdom of Impact", completed: false },
      { id: "11", title: "The Mystery of How", completed: false },
      { id: "12", title: "Giving and Receiving", completed: false },
      { id: "13", title: "The Power of Sincere Thanks", completed: false },
      { id: "14", title: "Starting Small", completed: false },
      { id: "15", title: "The Invitation to Try", completed: false },
    ],
  },
  {
    id: "ghost-in-the-machine",
    title: "The Ghost in the Machine",
    description: "The subconscious and the Great Within",
    depth: "Beginner",
    episodes: [
      { id: "1", title: "The Silent Partner", subtitle: "The architecture of your inner life", completed: true },
      { id: "2", title: "What You Feel, You Create", completed: false },
      { id: "3", title: "The Power of Attention", completed: false },
      { id: "4", title: "The Danger of Resistance", completed: false },
      { id: "5", title: "The Seeds You Plant", completed: false },
      { id: "6", title: "Feeling the Soul of an Idea", completed: false },
      { id: "7", title: "Faith as a Foundation", completed: false },
      { id: "8", title: "The Practice of Desire", completed: false },
      { id: "9", title: "The Trap of Comparison", completed: false },
      { id: "10", title: "The Art of Letting Go", completed: false },
      { id: "11", title: "The Quality of Your Thoughts", completed: false },
      { id: "12", title: "The Inner and the Outer", completed: false },
    ],
  },
  {
    id: "awakening-to-the-infinite",
    title: "Awakening to the Infinite",
    description: "Spiritual integration and universal alignment",
    depth: "Intermediate",
    episodes: [
      { id: "1", title: "The Reservoir of the Infinite", subtitle: "Opening the inner gate", completed: false },
      { id: "2", title: "The Law of Attraction", completed: false },
      { id: "3", title: "The Power of Thought", completed: false },
      { id: "4", title: "Oneness with the Infinite", completed: false },
      { id: "5", title: "The Practice of Silence", completed: false },
      { id: "6", title: "Faith as a Force", completed: false },
      { id: "7", title: "The Nature of Prosperity", completed: false },
      { id: "8", title: "The Power of Love", completed: false },
      { id: "9", title: "The Illusion of Separation", completed: false },
      { id: "10", title: "Intuition and Inner Guidance", completed: false },
      { id: "11", title: "Releasing Fear", completed: false },
      { id: "12", title: "The Power of Expectation", completed: false },
      { id: "13", title: "The Lotus Pond Within", completed: false },
      { id: "14", title: "The Nature of Health and Vitality", completed: false },
      { id: "15", title: "The Final Alignment", subtitle: "The practice of affirmation", completed: false },
    ],
  },
  {
    id: "architecture-of-character",
    title: "The Architecture of Character",
    description: "Self-mastery and personal sovereignty",
    depth: "Intermediate",
    episodes: [
      { id: "1", title: "The Sovereign Self", subtitle: "Ruler of your internal kingdom", completed: false },
      { id: "2", title: "The Law of Habit", completed: false },
      { id: "3", title: "The Power of Poise", completed: false },
      { id: "4", title: "The Alchemy of Emotions", completed: false },
      { id: "5", title: "The Lens of Concentration", completed: false },
      { id: "6", title: "The Integrity of the Blueprint", completed: false },
      { id: "7", title: "The Master's Will", completed: false },
      { id: "8", title: "The Creative Atmosphere", completed: false },
      { id: "9", title: "The Anatomy of Decision", completed: false },
      { id: "10", title: "The Mastery of Change", completed: false },
      { id: "11", title: "The Radiance of the Soul", completed: false },
      { id: "12", title: "The Law of Non-Interference", completed: false },
      { id: "13", title: "The Mastery of the Moment", completed: false },
      { id: "14", title: "The Great Achievement", completed: false },
      { id: "15", title: "The Final Seal", subtitle: "The eternal flame", completed: false },
    ],
  },
  {
    id: "resonance-of-one",
    title: "The Resonance of One",
    description: "Non-duality and the universal current",
    depth: "Deep",
    episodes: [
      { id: "1", title: "The Primal Vibration", subtitle: "Ik — the singularity that contains everything", completed: false },
      { id: "2", title: "The Sound of Silence", subtitle: "Anhad — the unstruck sound", completed: false },
      { id: "3", title: "The Ocean and the Drop", completed: false },
      { id: "4", title: "The Alchemy of Service", subtitle: "Seva", completed: false },
      { id: "5", title: "The Fearless State", subtitle: "Nirbhau", completed: false },
      { id: "6", title: "Cleaning the Mirror", subtitle: "Man Jeetai", completed: false },
      { id: "7", title: "The Garden of the Heart", completed: false },
      { id: "8", title: "The Eternal Signature", subtitle: "Sat", completed: false },
      { id: "9", title: "The Rhythm of the Breath", completed: false },
      { id: "10", title: "The Field of Influence", completed: false },
      { id: "11", title: "The Divine Play", subtitle: "Leela", completed: false },
      { id: "12", title: "Remaining Unstained", subtitle: "Lotus in the water", completed: false },
      { id: "13", title: "The Law of Inflow and Outflow", completed: false },
      { id: "14", title: "The Threshold of Transition", completed: false },
      { id: "15", title: "The Final Union", subtitle: "The marriage of soul and source", completed: false },
    ],
  },
  {
    id: "way-of-the-sovereign-creator",
    title: "The Way of the Sovereign Creator",
    description: "Integrated mastery and the creative will",
    depth: "Deep",
    episodes: [
      { id: "1", title: "The Zero Mind", subtitle: "Active stillness and infinite potential", completed: false },
      { id: "2", title: "The Command of Intention", completed: false },
      { id: "3", title: "The Flow of Excellence", completed: false },
      { id: "4", title: "The Magnetism of Truth", completed: false },
      { id: "5", title: "The Fearless Action", completed: false },
      { id: "6", title: "The Alchemy of Influence", completed: false },
      { id: "7", title: "The Law of Non-Attachment", completed: false },
      { id: "8", title: "The Creative Silence", completed: false },
      { id: "9", title: "The Rhythm of Rest", completed: false },
      { id: "10", title: "The Authority of Presence", completed: false },
      { id: "11", title: "The Legacy of the One", completed: false },
      { id: "12", title: "The Sovereign's Gratitude", completed: false },
      { id: "13", title: "The Final Union", subtitle: "The marriage of soul and source", completed: false },
      { id: "14", title: "The Eternal Return", completed: false },
      { id: "15", title: "The Master's Peace", subtitle: "The final seal", completed: false },
    ],
  },
  {
    id: "art-of-total-acceptance",
    title: "The Art of Total Acceptance",
    description: "The end of conflict and the beginning of flow",
    depth: "Deep",
    episodes: [
      { id: "1", title: "The Trap of Doing", subtitle: "Why effort alone cannot reach the infinite", completed: false },
      { id: "2", title: "The Logic of the Heart", completed: false },
      { id: "3", title: "Total Acceptance", subtitle: "Hukam", completed: false },
      { id: "4", title: "The Mirage of the Ego", completed: false },
      { id: "5", title: "Breaking the Seed", completed: false },
      { id: "6", title: "The Fragrance of the Soul", completed: false },
      { id: "7", title: "The Master's Laughter", completed: false },
      { id: "8", title: "The Path of Celebration", completed: false },
      { id: "9", title: "The Zen of Non-Planning", completed: false },
      { id: "10", title: "The Miracle of Awareness", completed: false },
      { id: "11", title: "The Sovereignty of Aloneness", completed: false },
      { id: "12", title: "The Zen of Direct Experience", completed: false },
      { id: "13", title: "From Problem to Mystery", completed: false },
      { id: "14", title: "The Gate of Emptiness", subtitle: "Shunyata", completed: false },
      { id: "15", title: "The Final Celebration", subtitle: "The dance of the One", completed: false },
    ],
  },
  {
    id: "quantum-leap",
    title: "The Quantum Leap",
    description: "Transcendence and the mastery of grace",
    depth: "Deep",
    episodes: [
      { id: "1", title: "The Death of the Question", subtitle: "From Why? to Aha!", completed: false },
      { id: "2", title: "The Logic of Madness", completed: false },
      { id: "3", title: "The First Kingdom", subtitle: "Dharam Khand", completed: false },
      { id: "4", title: "The Kingdom of Knowledge", subtitle: "Gyan Khand", completed: false },
      { id: "5", title: "The Power of Wonder", subtitle: "Vismad", completed: false },
      { id: "6", title: "The Kingdom of Effort", subtitle: "Saram Khand", completed: false },
      { id: "7", title: "The Kingdom of Grace", subtitle: "Karam Khand", completed: false },
      { id: "8", title: "The Mastery of the Void", subtitle: "Shunyata", completed: false },
      { id: "9", title: "The Kingdom of Truth", subtitle: "Sach Khand", completed: false },
      { id: "10", title: "The Soundless Sound", subtitle: "Anhad", completed: false },
      { id: "11", title: "The Final Dissolution", subtitle: "Fana", completed: false },
      { id: "12", title: "The Master of the Morning", completed: false },
    ],
  },
  {
    id: "architecture-of-resonance",
    title: "The Architecture of Resonance",
    description: "The science and spirituality of sound",
    depth: "Deep",
    episodes: [
      { id: "1", title: "The Primordial Code", subtitle: "Naad — the soundless sound that precedes all form", completed: false },
      { id: "2", title: "The Neural Recording", subtitle: "Sound as storage", completed: false },
      { id: "3", title: "The Healing Frequency", completed: false },
      { id: "4", title: "The Voice as a Surgical Tool", completed: false },
      { id: "5", title: "The Neural Re-Write", subtitle: "Listening as solving", completed: false },
      { id: "6", title: "The Silence Between the Notes", completed: false },
      { id: "7", title: "The Geometry of Harmony", subtitle: "Cymatics", completed: false },
      { id: "8", title: "The Binaural Bridge", subtitle: "Brainwave entrainment", completed: false },
      { id: "9", title: "The Final Symphony of the Self", completed: false },
    ],
  },
  {
    id: "it-works-1926",
    title: "It Works (1926)",
    description: "Practical intention training from RHJ",
    depth: "Beginner",
    episodes: [
      { id: "1", title: "What Do You Really Want?", completed: false },
      { id: "2", title: "The Power of Definite Intention", completed: false },
      { id: "3", title: "Thinking About What You Want", completed: false },
      { id: "4", title: "The Practice of Gratitude", completed: false },
      { id: "5", title: "Silence and Inner Communication", completed: false },
      { id: "6", title: "Doubt and How to Move Through It", completed: false },
      { id: "7", title: "The Importance of Choosing Your Circle", completed: false },
      { id: "8", title: "The Practice of Daily Attention", completed: false },
      { id: "9", title: "Recognizing Progress", completed: false },
      { id: "10", title: "The Caution of Intention", completed: false },
      { id: "11", title: "The Mystery of How", completed: false },
      { id: "12", title: "Giving and Receiving", completed: false },
      { id: "13", title: "The Power of Sincere Thanks", completed: false },
      { id: "14", title: "Starting Small", completed: false },
      { id: "15", title: "The Invitation to Try", completed: false },
    ],
  },
  {
    id: "the-great-within-1907",
    title: "The Great Within (1907)",
    description: "Inner laws of thought, feeling, and creation",
    depth: "Intermediate",
    episodes: [
      { id: "1", title: "Two Minds, One Life", completed: false },
      { id: "2", title: "What You Feel, You Create", completed: false },
      { id: "3", title: "The Power of Attention", completed: false },
      { id: "4", title: "The Danger of Resistance", completed: false },
      { id: "5", title: "The Seeds You Plant", completed: false },
      { id: "6", title: "Feeling the Soul of an Idea", completed: false },
      { id: "7", title: "Faith as a Foundation", completed: false },
      { id: "8", title: "The Practice of Desire", completed: false },
      { id: "9", title: "The Trap of Comparison", completed: false },
      { id: "10", title: "The Art of Letting Go", completed: false },
      { id: "11", title: "The Quality of Your Thoughts", completed: false },
      { id: "12", title: "The Inner and the Outer", completed: false },
      { id: "13", title: "The Power of Poise", completed: false },
      { id: "14", title: "The Gift of Sleep", completed: false },
      { id: "15", title: "The Awakening", completed: false },
    ],
  },
  {
    id: "in-tune-with-the-infinite-1897",
    title: "In Tune with the Infinite (1897)",
    description: "Meditation arc on alignment, flow, and spiritual law",
    depth: "Deep",
    episodes: [
      { id: "1", title: "The Two Sides of Your Mind", completed: false },
      { id: "2", title: "The Law of Attraction", completed: false },
      { id: "3", title: "Opening to the Infinite", completed: false },
      { id: "4", title: "The Power of Thought", completed: false },
      { id: "5", title: "Oneness with the Infinite", completed: false },
      { id: "6", title: "The Practice of Silence", completed: false },
      { id: "7", title: "Faith as a Force", completed: false },
      { id: "8", title: "The Nature of Prosperity", completed: false },
      { id: "9", title: "The Power of Love", completed: false },
      { id: "10", title: "The Illusion of Separation", completed: false },
      { id: "11", title: "Intuition and Inner Guidance", completed: false },
      { id: "12", title: "The Practice of Gratitude", completed: false },
      { id: "13", title: "Releasing Fear", completed: false },
      { id: "14", title: "The Power of Expectation", completed: false },
      { id: "15", title: "The Lotus Pond Within", completed: false },
      { id: "16", title: "The Nature of Health", completed: false },
      { id: "17", title: "The Practice of Affirmation", completed: false },
      { id: "18", title: "The Law of Giving and Receiving", completed: false },
      { id: "19", title: "The Power of Presence", completed: false },
      { id: "20", title: "The Nature of Desire", completed: false },
      { id: "21", title: "The Practice of Meditation", completed: false },
      { id: "22", title: "The Power of Visualization", completed: false },
      { id: "23", title: "The Nature of Character", completed: false },
      { id: "24", title: "The Power of Service", completed: false },
      { id: "25", title: "The Nature of Success", completed: false },
      { id: "26", title: "The Practice of Forgiveness", completed: false },
      { id: "27", title: "The Power of Belief", completed: false },
      { id: "28", title: "The Nature of Harmony", completed: false },
      { id: "29", title: "The Power of Attention", completed: false },
    ],
  },
];
